const SABIL_CHANGE_TYPES = {
  CLOSE: "CLOSE",
  TRANSFER_WITHIN_JAMAAT: "TRANSFER_WITHIN_JAMAAT",
  TRANSFER_OUT: "TRANSFER_OUT",
};

const SABIL_CHANGE_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DECLINED: "DECLINED",
};
module.exports = {
  SABIL_CHANGE_TYPES,
  SABIL_CHANGE_STATUS,
};
