const MIQAATS = [
  {
    month: 0,
    day: 11,
    slots: ["Evening"],
    event: "Imam Husain (as) Siyum",
  },
  {
    month: 0,
    day: 15,
    slots: ["Evening"],
    event: "Urus - Syedna Hatim Mohiyeddin Aqa (ra)",
  },
  {
    month: 0,
    day: 22,
    slots: ["Evening"],
    event: "Urus - Syedi Hasanfeer Shaheed (aq)",
  },
  {
    month: 0,
    day: 26,
    slots: ["Evening"],
    event: "Urus - Syedi Fakhruddin Shaheed (aq)",
  },
  {
    month: 1,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 1,
    day: 19,
    slots: ["Evening"],
    event: "Imam Husain (as) Chehlum",
  },
  {
    month: 1,
    day: 27,
    slots: ["Evening"],
    event: "Imam Hasan (as) Shahadat",
  },
  {
    month: 2,
    day: 11,
    slots: ["Evening"],
    event: "Milad-un-Nabi (saw)",
  },
  {
    month: 2,
    day: 13,
    slots: ["Evening"],
    event: "SMB Khatmul Qur'an Majlis",
  },
  {
    month: 2,
    day: 14,
    slots: ["Evening"],
    event: "SMB Khatmul Qur'an Majlis",
  },
  {
    month: 2,
    day: 15,
    slots: ["Evening"],
    event: "Urus - Syedna Mohammed Burhanuddin Aqa (ra)",
  },
  {
    month: 3,
    day: 3,
    slots: ["Evening"],
    event: "Milad Imam-uz-Zamaan (as)",
  },
  {
    month: 3,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 3,
    day: 19,
    slots: ["Evening"],
    event: "Milad Syedna Mohammed Burhanuddin Aqa (ra)",
  },
  {
    month: 4,
    day: 9,
    slots: ["Evening"],
    event: "Maulatena Fatema-uz-Zahra (as)",
  },
  {
    month: 4,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 5,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 5,
    day: 22,
    slots: ["Evening"],
    event: "Urus - Syedna Ismail Badruddin Aqa (ra)",
  },
  {
    month: 5,
    day: 26,
    slots: ["Evening"],
    event: "Urus - Syedna Qutubkhan Qutbuddin Shaheed (ra)",
  },
  {
    month: 6,
    day: 3,
    slots: ["Evening"],
    event: "Urus - Syedna NoorMohammed Nooruddin Aqa (ra)",
  },
  {
    month: 6,
    day: 12,
    slots: ["Evening"],
    event: "Milad Ameer-il-Mumineen (as)",
  },
  {
    month: 6,
    day: 16,
    slots: ["Evening"],
    event: "STS Khatmul Qur'an Majlis",
  },
  {
    month: 6,
    day: 17,
    slots: ["Evening"],
    event: "STS Khatmul Qur'an Majlis",
  },
  {
    month: 6,
    day: 18,
    slots: ["Evening"],
    event: "Urus - Syedna Taher Saifuddin Aqa (ra)",
  },
  {
    month: 6,
    day: 27,
    slots: ["Evening"],
    event: "Mearaj Iftar",
  },
  {
    month: 7,
    day: 21,
    slots: ["Evening"],
    event: "Urus - Maulatena Hurrat-ul-Maleka (aq)",
  },
  {
    month: 8,
    day: null,
    slots: ["Evening"],
    event: "Shehrullah-il-moazzam",
  },
  {
    month: 9,
    day: 4,
    slots: ["Evening"],
    event: "Urus - Syedi Abdulqader Hakimuddin Aqa (aq)",
  },
  {
    month: 9,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 9,
    day: 26,
    slots: ["Evening"],
    event: "Urus - Syedi Abdulqader Hakimuddin Aqa (aq)",
  },
  {
    month: 10,
    day: 11,
    slots: ["Evening"],
    event: "Urus - Syedna Abdeali Saifuddin Aqa (ra)",
  },
  {
    month: 10,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 10,
    day: 26,
    slots: ["Evening"],
    event: "Milad Syedna Taher Saifuddin Aqa (ra)",
  },
  {
    month: 11,
    day: 15,
    slots: ["Evening"],
    event: "Darees + Documentary",
  },
  {
    month: 11,
    day: 18,
    slots: ["Evening"],
    event: "Eid-e-Gadeer Iftar",
  },
];

module.exports = MIQAATS;
